=== Aion-server/Aion-unique/AE-go_GameServer/data/static_data/world_maps.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="world_maps">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="map" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence />
						<xs:attribute name="name" type="xs:string" />
						<xs:attribute name="id" type="xs:int" use="required" />
						<xs:attribute name="twin_count" type="xs:int" />
						<xs:attribute name="max_user" type="xs:int" />
						<xs:attribute name="prison" type="xs:boolean" />
						<xs:attribute name="instance" type="xs:boolean" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Aion-server/Aion-unique/AE-go_GameServer/data/static_data/world_maps.xml
<?xml version="1.0" encoding="UTF-8"?>
<world_maps xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="world_maps.xsd">
	<map id="110010000" name="Sanctum" death_level="400" water_level="16"/>
	<map id="120010000" name="Pandaemonium" death_level="150" water_level="16"/>
	<map id="210010000" name="Poeta" max_user="200" twin_count="2" death_level="0" water_level="100"/>
	<map id="210030000" name="Verteron" max_user="200" death_level="0" water_level="100"/>
	<map id="210020000" name="Eltnen" death_level="0" water_level="6"/>
	<map id="210060000" name="Theomobos" death_level="0" water_level="1"/>
	<map id="210040000" name="Heiron" death_level="0" water_level="100"/>
	<map id="220010000" name="Ishalgen" max_user="200" twin_count="2" death_level="0" water_level="248"/>
	<map id="220030000" name="Altgard" max_user="200" death_level="0" water_level="248"/>
	<map id="220020000" name="Morheim" death_level="0" water_level="16"/>
	<map id="220050000" name="Brusthonin" death_level="0" water_level="5"/>
	<map id="220040000" name="Beluslan" death_level="0" water_level="16"/>
	<map id="300010000" name="IDAbPro" death_level="0" water_level="16"/>
	<map id="300030000" name="NochsanaTrainingCamp" instance="true" death_level="0" water_level="16"/>
	<map id="300040000" name="DarkPoeta" instance="true" death_level="0" water_level="16"/>
	<map id="300050000" name="AstreiaChamber" instance="true" death_level="0" water_level="16"/>
	<map id="300060000" name="SulfurTreeNest" instance="true" death_level="0" water_level="16"/>
	<map id="300070000" name="ChamberOfRoah" instance="true" death_level="0" water_level="16"/>
	<map id="300080000" name="LeftWingChamber" instance="true" death_level="0" water_level="16"/>
	<map id="300090000" name="RightWingChamber" instance="true" death_level="0" water_level="16"/>
	<map id="300100000" name="SteelRake" instance="true" death_level="0" water_level="16"/>
	<map id="300110000" name="Dredgion" instance="true" death_level="0" water_level="16"/>
	<map id="300120000" name="KysisChamber" instance="true" death_level="0" water_level="16"/>
	<map id="300130000" name="MirenChamber" instance="true" death_level="0" water_level="16"/>
	<map id="300140000" name="KrotanChamber" instance="true" death_level="0" water_level="16"/>
	<map id="310010000" name="IDAbProL1" instance="true" death_level="0" water_level="16"/>
	<map id="310020000" name="IDAbProL2" instance="true" death_level="0" water_level="16"/>
	<map id="310030000" name="IDAbGateL1" death_level="0" water_level="16"/>
	<map id="310040000" name="IDAbGateL2" death_level="0" water_level="16"/>
	<map id="310050000" name="IDLF3Lp" instance="true" death_level="0" water_level="16"/>
	<map id="310060000" name="IDLF1B" death_level="0" water_level="16"/>
	<map id="310070000" name="IDLF1B_Stigma" death_level="0" water_level="16"/>
	<map id="310080000" name="IDLC1_arena" death_level="0" water_level="16"/>
	<map id="310090000" name="IDLF3_Castle_indratoo" death_level="0" water_level="16"/>
	<map id="310100000" name="IDLF3_Castle_Lehpar" instance="true" death_level="0" water_level="16"/>
	<map id="310110000" name="TheobomosLab" instance="true" death_level="0" water_level="16"/>
	<map id="320010000" name="IDAbProD1" instance="true" death_level="0" water_level="16"/>
	<map id="320020000" name="IDAbProD2" instance="true" death_level="0" water_level="16"/>
	<map id="320030000" name="IDAbGateD1" death_level="0" water_level="16"/>
	<map id="320040000" name="IDAbGateD2" death_level="0" water_level="16"/>
	<map id="320050000" name="IDDF2Flying" death_level="0" water_level="16"/>
	<map id="320060000" name="IDDF1B" death_level="0" water_level="16"/>
	<map id="320070000" name="IDSpace" death_level="0" water_level="16"/>
	<map id="320080000" name="IDDF3_Dragon" instance="true" death_level="0" water_level="16"/>
	<map id="320090000" name="IDDC1_arena" death_level="0" water_level="16"/>
	<map id="320100000" name="IDDF2_Dflame" instance="true" death_level="0" water_level="16"/>
	<map id="320110000" name="IDDF3_LP" instance="true" death_level="0" water_level="16"/>
	<map id="320120000" name="IDDC1_Arena_3F" death_level="0" water_level="16"/>
	<map id="320130000" name="AdmaStronghold" instance="true" death_level="0" water_level="16"/>
	<map id="400010000" name="Ab1" death_level="0" water_level="16"/>
	<map id="510010000" prison="true" name="LF_Prison" death_level="0" water_level="16"/>
	<map id="520010000" prison="true" name="DF_Prison" death_level="0" water_level="16"/>
	<map id="900020000" twin_count="10" name="Test_Basic" death_level="0" water_level="16"/>
	<map id="900030000" twin_count="5" name="Test_Server" death_level="0" water_level="1"/>
	<map id="900100000" name="Test_GiantMonster" death_level="0" water_level="16"/>
</world_maps>
