=== Aion-server/Aion-unique/AE-go_GameServer/data/static_data/portals/portal_templates.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="../import.xsd" />
	<xs:include schemaLocation="../global_types.xsd" />

	<xs:element name="portal_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="portal" type="Portal" minOccurs="0"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Portal">
		<xs:sequence>
			<xs:element name="entrypoint" type="EntryPoint" minOccurs="1"
				maxOccurs="2" />
			<xs:element name="exitpoint" type="ExitPoint" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="portalitem" type="PortalItem" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="race" type="Race" />
		<xs:attribute name="group" type="xs:boolean" />
		<xs:attribute name="maxlevel" type="xs:int" />
		<xs:attribute name="minlevel" type="xs:int" />
		<xs:attribute name="instance" type="xs:boolean" />
		<xs:attribute name="npcid" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="EntryPoint">
		<xs:attribute name="mapid" type="xs:int" />
		<xs:attribute name="x" type="xs:float" />
		<xs:attribute name="y" type="xs:float" />
		<xs:attribute name="z" type="xs:float" />
		<xs:attribute name="race" type="Race" />
	</xs:complexType>

	<xs:complexType name="ExitPoint">
		<xs:attribute name="mapid" type="xs:int" />
		<xs:attribute name="x" type="xs:float" />
		<xs:attribute name="y" type="xs:float" />
		<xs:attribute name="z" type="xs:float" />
	</xs:complexType>

	<xs:complexType name="PortalItem">
		<xs:attribute name="id" type="xs:int" />
		<xs:attribute name="itemid" type="xs:int" />
		<xs:attribute name="quantity" type="xs:int" />
	</xs:complexType>
	
</xs:schema>

=== Aion-server/Aion-unique/AE-go_GameServer/data/static_data/portals/portal_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<portal_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="portal_templates.xsd">
	
	<!-- INSTANCES -->
	
	<!--Chamber of Roah -->
	<portal npcid="700479" instance="true" minlevel="40" maxlevel="50" group="true">
		<entrypoint mapid="400010000" x="2712.53" y="757.89" z="2854.295"/>
		<exitpoint mapid="300070000" x="503.74" y="395.70" z="94.34"/>
	</portal>
	
	<!-- Alquimia Research Center Entrance -->
   <portal npcid="730110"  instance="true" minlevel="41" maxlevel="44" group="true">
      <entrypoint mapid="220040000" x="2203.19" y="2923.57" z="699.81"/>
      <exitpoint mapid="320110000" x="602.62976" y="526.6474" z="200.05792"/>
   </portal>
	
	<!-- Nochsana Training Camp Asmodians -->
	<portal npcid="700414"  instance="true" minlevel="25" maxlevel="28" group="true" race="ASMODIANS">
		<entrypoint mapid="400010000" x="876.7211" y="3079.2874" z="1644.5786" race="ASMODIANS"/>
		<exitpoint mapid="300030000" x="513" y="668" z="331"/>
	</portal>
	
	<!-- Nochsana Training Camp Elyos -->
	<portal npcid="700413" instance="true" minlevel="25" maxlevel="28" group="true" race="ELYOS">
		<entrypoint mapid="400010000" x="2890" y="754" z="1498.5786" race="ELYOS"/>
		<exitpoint mapid="300030000" x="513" y="668" z="331"/>
	</portal>
	
	<!-- Fire Temple-->
	<portal npcid="730047" instance="true" minlevel="25" group="true" maxlevel="50">
		<entrypoint mapid="220020000" x="1592.178" y="977.2572" z="140.75" race="ASMODIANS"/>
		<entrypoint mapid="210020000" x="1343.28" y="350.96" z="348.67" race="ELYOS"/>
		<exitpoint mapid="320100000" x="148.256" y="460.857" z="141.713"/>
	</portal>
	
	<!-- Draupnir Cave Entrance -->
	<portal npcid="700370" instance="true" minlevel="44" maxlevel="50" group="true">
		<entrypoint mapid="220040000" x="1605.27" y="2729.9" z="705.345"/>
		<exitpoint mapid="320080000" x="491" y="373" z="622"/>
	</portal>
	
	<!-- Artifact of Circulation / DarkPoeta -->
	<portal npcid="730185" instance="true" minlevel="40" maxlevel="50" group="true" race="ASMODIANS">
		<entrypoint mapid="220040000" x="2420.12" y="2061.31" z="579.7" race="ASMODIANS"/>
		<exitpoint mapid="300040000" x="1214" y="412" z="140"/>
		<portalitem id="1" itemid="186000048" quantity="20"/>
		<portalitem id="2" itemid="186000050" quantity="1"/>
	</portal>
	
	<!-- Artifact of Transcendence / DarkPoeta -->
	<portal npcid="730186" instance="true" minlevel="40" maxlevel="50" group="true" race="ELYOS">
		<entrypoint mapid="210040000" x="2019.51" y="1467.34" z="127.19" race="ELYOS"/>
		<exitpoint mapid="300040000" x="1214" y="412" z="140"/>
		<portalitem id="1" itemid="186000048" quantity="20"/>
		<portalitem id="2" itemid="186000050" quantity="1"/>
	</portal>
	
	<!-- Artifact of Time / DarkPoeta -->
	<portal npcid="730215" instance="true" minlevel="40" maxlevel="50" group="true">
		<entrypoint mapid="400010000" x="2158" y="1581" z="2272.5"/>
		<exitpoint mapid="300040000" x="1214" y="412" z="140"/>
		<portalitem id="1" itemid="186000048" quantity="5"/>
		<portalitem id="2" itemid="186000050" quantity="1"/>
	</portal>
	
	<!-- QUEST PORTALS -->
	
	<!-- Pernos [Ascension quest] Elyos -->
	<portal npcid="790001" instance="true" race="ELYOS">
		<entrypoint mapid="210010000" x="241.094" y="1639.461" z="100.38" race="ELYOS"/>
		<exitpoint mapid="310010000" x="52" y="174" z="229"/>
	</portal>
	
	<!-- Munin [Ascension quest] Asmodians -->
	<portal npcid="203550" instance="true" race="ASMODIANS">
		<entrypoint mapid="220010000" x="378.9" y="1895.39" z="330.0" race="ASMODIANS"/>
		<exitpoint mapid="320010000" x="457.65" y="426.8" z="230.4"/>
	</portal>
	
	<!-- ABYSS GATES -->
	
	<!-- Verteron to Abyss -->
	<portal npcid="700088" minlevel="25" maxlevel="50" instance="false" group="false" race="ELYOS">
		<entrypoint mapid="210030000" x="0" y="0" z="0" race="ELYOS"/>
		<exitpoint mapid="400010000" x="2867" y="1036" z="1528"/>
	</portal>
	
	<!-- Eltnen to Abyss -->
	<portal npcid="700177" minlevel="25" maxlevel="50" instance="false" group="false" race="ELYOS">
		<entrypoint mapid="210020000" x="0" y="0" z="0" race="ELYOS"/>
		<exitpoint mapid="400010000" x="2867" y="1036" z="1528"/>
	</portal>
	
	<!-- Heiron to Abyss -->
	<portal npcid="700360" minlevel="25" maxlevel="50" instance="false" group="false" race="ELYOS">
		<entrypoint mapid="210040000" x="0" y="0" z="0" race="ELYOS"/>
		<exitpoint mapid="400010000" x="2867" y="1036" z="1528"/>
	</portal>

	<!-- Abyss to Verteron -->
	<portal npcid="730073" minlevel="25" maxlevel="50" instance="false" group="false" race="ELYOS">
		<entrypoint mapid="400010000" x="0" y="0" z="0" race="ELYOS"/>
		<exitpoint mapid="210030000" x="1643" y="1500" z="119"/>
	</portal>
	
	<!-- Abyss to Eltnen -->
	<portal npcid="730074" minlevel="25" maxlevel="50" instance="false" group="false" race="ELYOS">
		<entrypoint mapid="400010000" x="0" y="0" z="0" race="ELYOS"/>
		<exitpoint mapid="210020000" x="343" y="2724" z="264"/>
	</portal>
	
	<!-- Abyss to Heiron -->
	<portal npcid="730075" minlevel="25" maxlevel="50" instance="false" group="false" race="ELYOS">
		<entrypoint mapid="400010000" x="0" y="0" z="0" race="ELYOS"/>
		<exitpoint mapid="210040000" x="2540" y="343" z="411"/>
	</portal>
	
	<!-- Morheim to Abyss -->
	<portal npcid="700183" minlevel="25" maxlevel="50" instance="false" group="false" race="ASMODIANS">
		<entrypoint mapid="220020000" x="0" y="0" z="0" race="ASMODIANS"/>
		<exitpoint mapid="400010000" x="1078" y="2839" z="1636"/>
	</portal>
	
	<!-- Beluslan to Abyss -->
	<portal npcid="730064" minlevel="25" maxlevel="50" instance="false" group="false" race="ASMODIANS">
		<entrypoint mapid="220040000" x="0" y="0" z="0" race="ASMODIANS"/>
		<exitpoint mapid="400010000" x="1078" y="2839" z="1636"/>
	</portal>
	
	<!-- Altgard to Abyss -->
	<portal npcid="700089" minlevel="25" maxlevel="50" instance="false" group="false" race="ASMODIANS">
		<entrypoint mapid="220030000" x="0" y="0" z="0" race="ASMODIANS"/>
		<exitpoint mapid="400010000" x="1078" y="2839" z="1636"/>
	</portal>
	
	<!-- Abyss to Morheim -->
	<portal npcid="730077" minlevel="25" maxlevel="50" instance="false" group="false" race="ASMODIANS">
		<entrypoint mapid="400010000" x="0" y="0" z="0" race="ASMODIANS"/>
		<exitpoint mapid="220020000" x="308" y="2274" z="449"/>
	</portal>
	
	<!-- Abyss to Beluslan -->
	<portal npcid="730078" minlevel="25" maxlevel="50" instance="false" group="false" race="ASMODIANS">
		<entrypoint mapid="400010000" x="0" y="0" z="0" race="ASMODIANS"/>
		<exitpoint mapid="220040000" x="325" y="336" z="229"/>
	</portal>	
	
	<!-- Abyss to Altgard -->
	<portal npcid="730076" minlevel="25" maxlevel="50" instance="false" group="false" race="ASMODIANS">
		<entrypoint mapid="400010000" x="0" y="0" z="0" race="ASMODIANS"/>
		<exitpoint mapid="220030000" x="1748" y="1807" z="254"/>
	</portal>
	
	<!-- SCROLL TELEPORTS  ELYOS-->
	
	<portal name="LF1A_RETURN_AREA_1">
		<exitpoint mapid="210030000" x="1690.4" y="1481.4" z="121.4"/>
	</portal>
	
	<portal name="LC1_RETURN_AREA_1">
		<exitpoint mapid="110010000" x="1476.3" y="1595.5" z="572.9"/>
	</portal>
	
	<portal name="LF2_RETURN_AREA">
		<exitpoint mapid="210020000" x="285.4" y="2750.8" z="270.5"/>
	</portal>
	
	<portal name="LF3_RETURN_AREA_1">
		<exitpoint mapid="210040000" x="2469.6" y="304.2" z="415.62418"/>
	</portal>
	
	<!-- SCROLL TELEPORTS  ELYOS END-->
	
	<!-- SCROLL TELEPORTS ASMODIANS-->
	
	<portal name="DC1_RETURN_AREA_1">
		<exitpoint mapid="120010000" x="1456.9" y="1417.0" z="177.5"/>
	</portal>
	
	<portal name="DF1A_RETURN_AREA">
		<exitpoint mapid="220030000" x="1661.2" y="1816.3" z="253.712"/>
	</portal>

	<portal name="DF2_RETURN_AREA_1">
		<exitpoint mapid="220020000" x="270.9" y="2339.6" z="443.74"/>
	</portal>

	<portal name="DF3_RETURN_AREA_1">
		<exitpoint mapid="220040000" x="321.8" y="335.0" z="229.9"/>
	</portal>
	
	<!-- SCROLL TELEPORTS ASMODIANS END-->
	
	
</portal_templates>
